### ISSUE TITLE
Nachreichungen

### ISSUE THREAD

**Issue by pabay101** [ProPra16/programmierpraktikum-abschlussprojekt-something-normal-1#2]
Das Projekt ist momentan mangelhaft. Ihr müsst folgendes nachreichen:
- Eine Zuordnung von euren Github-Nicknames und euren Namen (außerdem gibt es Commits von "Katarzyna Rzońca", wer ist das?)
- Ein Benutzerhandbuch
- In Phase Green die Möglichkeit, zurück zu Red zu wechseln (mit Löschen des neuen Codes)
- Tracking _oder_ ATDD
- Vor allem @LorcanMacKee und @Batuu13 haben soweit ich das sehen kann bisher sehr wenig mitgearbeitet, von euch beiden muss der größere Anteil der Programmierung kommen.

Alles, was ihr bis einschließlich Sonntag, den 24. Juli eingereicht habt, werde ich garantiert korrigieren. Danach eventuell auch noch, allerdings ohne Garantie!

**Comment by LorcanMacKee** [comment]
Our  nicks and real names:
Katarzyna Rzońca, kasia12345
Batuhan Yaman, (Batuu13)
LorcanMacKee, Luca D. Neumann
fuempf, Karol Actun,

**Comment by pabay101** [comment]
Ihr habt jetzt dieses Projekt bestanden, das wird im Auas allerdings von Jens direkt eingetragen, darum kann es sein, dass es sich dort noch verzögert.
